### ISSUE TITLE
Silver and Orange Line metro stops 

### ISSUE THREAD

**Issue by sk8carl** [bikeablebrews/wod#1]
bikeablebrews/wod is a great resource!

This is more of a comment than an issue.  Since it is possible to have a couple too many brews along the trail, it may be helpful to include the Metro stations that are near the W&OD...just in case.

thanks again for the cool website!

**Comment by dmofot** [comment]
Let me see what I can find.  If the data exists, it shouldn't be too hard to add as a reference layer that is off by default.  Thanks!

**Comment by dmofot** [comment]
Adding all the metro stops is definitely ugly, as there are so many of them not near the trail.  It's easy enough to pick and choose though, only adding the Silver line and half the Orange line, but it might not be the best idea to include incomplete information.  I created a separate branch for testing, so play with it and let me know what you think:

http://dmofot.github.io/bikeablebrews/metro.html

If you zoom in close enough and turn off the station layers, you can see the stations are already on the basemap tiles, but they are made to blend well with the other infrastructure items.  Ultimately, the best way is probably redesigning the basemap tiles to make the station icons more prominent, but that won't be happening anytime soon.
